<a href="https://colab.research.google.com/github/Nivetha72006/Clustering-Algorithms/blob/main/Association_Rule_Mining_for_Market_Basket_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [7]:
df=pd.read_csv("/content/Market_Basket_Optimisation.csv",header=None)

In [8]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.tail()

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
7495,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7496,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   shrimp             7500 non-null   object
 1   almonds            5746 non-null   object
 2   avocado            4388 non-null   object
 3   vegetables mix     3344 non-null   object
 4   green grapes       2528 non-null   object
 5   whole weat flour   1863 non-null   object
 6   yams               1368 non-null   object
 7   cottage cheese     980 non-null    object
 8   energy drink       653 non-null    object
 9   tomato juice       394 non-null    object
 10  low fat yogurt     255 non-null    object
 11  green tea          153 non-null    object
 12  honey              86 non-null     object
 13  salad              46 non-null     object
 14  mineral water      24 non-null     object
 15  salmon             7 non-null      object
 16  antioxydant juice  3 non-null      object
 17  frozen smoothie    3 non-null      object
 18  spinach            2 non-null      object
 19  olive oil          0 non-null      float64
dtypes: float64(1), object(19)
memory usage: 1.1+ MB

In [24]:
transaction=[]
for i in range(0,len(df)):
  transaction.append([str(df.values[i,j])for j in range(0,20)if str(df.values[i,j])!='nan'])

In [25]:
transaction

[['shrimp',
  'almonds',
  'avocado',
  'vegetables mix',
  'green grapes',
  'whole weat flour',
  'yams',
  'cottage cheese',
  'energy drink',
  'tomato juice',
  'low fat yogurt',
  'green tea',
  'honey',
  'salad',
  'mineral water',
  'salmon',
  'antioxydant juice',
  'frozen smoothie',
  'spinach',
  'olive oil'],
 ['burgers', 'meatballs', 'eggs'],
 ['chutney'],
 ['turkey', 'avocado'],
 ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea'],
 ['low fat yogurt'],
 ['whole wheat pasta', 'french fries'],
 ['soup', 'light cream', 'shallot'],
 ['frozen vegetables', 'spaghetti', 'green tea'],
 ['french fries'],
 ['eggs', 'pet food'],
 ['cookies'],
 ['turkey', 'burgers', 'mineral water', 'eggs', 'cooking oil'],
 ['spaghetti', 'champagne', 'cookies'],
 ['mineral water', 'salmon'],
 ['mineral water'],
 ['shrimp',
  'chocolate',
  'chicken',
  'honey',
  'oil',
  'cooking oil',
  'low fat yogurt'],
 ['turkey', 'eggs'],
 ['turkey',
  'fresh tuna',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'black tea',
  'salmon',
  'eggs',
  'chicken',
  'extra dark chocolate'],
 ['meatballs', 'milk', 'honey', 'french fries', 'protein bar'],
 ['red wine', 'shrimp', 'pasta', 'pepper', 'eggs', 'chocolate', 'shampoo'],
 ['rice', 'sparkling water'],
 ['spaghetti', 'mineral water', 'ham', 'body spray', 'pancakes', 'green tea'],
 ['burgers',
  'grated cheese',
  'shrimp',
  'pasta',
  'avocado',
  'honey',
  'white wine',
  'toothpaste'],
 ['eggs'],
 ['parmesan cheese', 'spaghetti', 'soup', 'avocado', 'milk', 'fresh bread'],
 ['ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'energy bar',
  'black tea',
  'salmon',
  'frozen smoothie',
  'escalope'],
 ['sparkling water'],
 ['mineral water', 'eggs', 'chicken', 'chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'yams', 'mineral water'],
 ['herb & pepper', 'tomato sauce', 'light cream', 'magazines'],
 ['mineral water', 'chocolate', 'avocado', 'eggs'],
 ['turkey', 'french fries', 'strawberries'],
 ['frozen vegetables', 'strong cheese', 'chocolate'],
 ['cookies'],
 ['pickles', 'spaghetti', 'salmon', 'escalope'],
 ['energy bar', 'french fries'],
 ['red wine', 'ground beef', 'mineral water'],
 ['mineral water', 'cake', 'cottage cheese'],
 ['pickles', 'champagne', 'green tea'],
 ['spaghetti'],
 ['fresh tuna',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'honey',
  'whole wheat rice',
  'frozen smoothie',
  'escalope'],
 ['spaghetti'],
 ['soup', 'meatballs', 'hot dogs', 'sparkling water'],
 ['escalope'],
 ['soup',
  'avocado',
  'french fries',
  'hot dogs',
  'brownies',
  'body spray',
  'pancakes',
  'green tea'],
 ['mineral water', 'chicken', 'cereals', 'clothes accessories'],
 ['mineral water', 'bug spray'],
 ['avocado', 'muffins'],
 ['burgers', 'black tea', 'green tea'],
 ['spaghetti', 'chocolate', 'brownies', 'white wine', 'green tea'],
 ['fresh tuna', 'mineral water', 'eggs'],
 ['spaghetti', 'muffins'],
 ['spaghetti', 'chocolate'],
 ['french fries', 'escalope', 'champagne'],
 ['tomato sauce', 'light mayo'],
 ['turkey',
  'fresh tuna',
  'frozen vegetables',
  'tomatoes',
  'ground beef',
  'spaghetti',
  'mineral water',
  'chocolate',
  'soup',
  'milk',
  'olive oil'],
 ['eggs', 'cookies'],
 ['soup',
  'chicken',
  'gums',
  'soda',
  'body spray',
  'energy drink',
  'green tea'],
 ['turkey',
  'frozen vegetables',
  'mineral water',
  'cider',
  'cooking oil',
  'green tea'],
 ['spaghetti'],
 ['clothes accessories'],
 ['energy drink'],
 ['soup', 'bug spray', 'shallot', 'protein bar', 'green tea'],
 ['turkey', 'eggs'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'avocado',
  'cider',
  'whole wheat rice'],
 ['cookies'],
 ['shrimp', 'pasta'],
 ['grated cheese', 'herb & pepper', 'tomatoes', 'tomato sauce', 'corn'],
 ['burgers', 'escalope', 'shallot'],
 ['cookies'],
 ['yogurt cake'],
 ['soup', 'eggs'],
 ['cookies'],
 ['mineral water', 'chocolate', 'low fat yogurt'],
 ['eggs', 'strawberries'],
 ['grated cheese', 'ground beef', 'spaghetti', 'mineral water', 'white wine'],
 ['mint'],
 ['eggs', 'cake', 'french fries'],
 ['burgers', 'spaghetti', 'milk', 'french fries', 'green tea'],
 ['mineral water', 'energy bar', 'butter', 'french fries'],
 ['burgers',
  'grated cheese',
  'herb & pepper',
  'mineral water',
  'eggs',
  'cooking oil'],
 ['energy bar'],
 ['energy bar', 'energy drink'],
 ['chocolate', 'frozen smoothie'],
 ['low fat yogurt'],
 ['asparagus', 'salad'],
 ['burgers', 'french fries', 'low fat yogurt', 'green tea'],
 ['low fat yogurt'],
 ['burgers',
  'herb & pepper',
  'shrimp',
  'pasta',
  'spaghetti',
  'mineral water',
  'meatballs',
  'olive oil',
  'energy bar',
  'french wine',
  'eggs',
  'salt'],
 ['champagne', 'low fat yogurt'],
 ['champagne'],
 ['burgers', 'almonds', 'eggs', 'french fries', 'cookies', 'green tea'],
 ['ham', 'soup', 'escalope', 'body spray'],
 ['turkey',
  'ham',
  'frozen vegetables',
  'pepper',
  'oil',
  'extra dark chocolate',
  'tea',
  'magazines'],
 ['muffins', 'eggs', 'cookies'],
 ['cookies'],
 ['frozen vegetables',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'chocolate',
  'green tea'],
 ['mineral water', 'barbecue sauce', 'chocolate'],
 ['burgers',
  'herb & pepper',
  'energy bar',
  'almonds',
  'eggs',
  'corn',
  'mayonnaise',
  'zucchini'],
 ['turkey',
  'burgers',
  'ground beef',
  'chocolate',
  'soup',
  'almonds',
  'eggs',
  'hot dogs',
  'cottage cheese'],
 ['ham', 'spaghetti', 'chocolate', 'eggs'],
 ['ground beef', 'energy bar', 'pet food', 'carrots', 'protein bar'],
 ['ground beef',
  'tomato sauce',
  'spaghetti',
  'mineral water',
  'almonds',
  'eggs'],
 ['mineral water', 'olive oil', 'gums', 'cooking oil'],
 ['shrimp',
  'pasta',
  'mineral water',
  'soup',
  'avocado',
  'milk',
  'olive oil',
  'green grapes',
  'eggs',
  'bug spray'],
 ['shrimp',
  'pasta',
  'soup',
  'cake',
  'cooking oil',
  'chicken',
  'light mayo',
  'low fat yogurt'],
 ['spaghetti',
  'mineral water',
  'chocolate',
  'french fries',
  'champagne',
  'escalope',
  'mushroom cream sauce',
  'fresh bread'],
 ['shrimp', 'pasta', 'mineral water', 'eggs'],
 ['burgers', 'oil', 'tomato juice', 'fresh bread'],
 ['french wine', 'eggs', 'chocolate', 'low fat yogurt'],
 ['chicken', 'eggs', 'french fries', 'pancakes'],
 ['turkey', 'herb & pepper', 'salmon', 'white wine', 'candy bars'],
 ['grated cheese',
  'spaghetti',
  'olive oil',
  'eggs',
  'french fries',
  'green tea'],
 ['mineral water', 'energy bar'],
 ['eggs', 'french fries'],
 ['burgers',
  'tomatoes',
  'mineral water',
  'soup',
  'milk',
  'almonds',
  'eggs',
  'chocolate',
  'tomato juice'],
 ['muffins'],
 ['pasta'],
 ['tomatoes', 'spaghetti', 'frozen smoothie'],
 ['ground beef', 'spaghetti', 'milk'],
 ['french fries'],
 ['chocolate', 'milk'],
 ['burgers',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'spaghetti',
  'mineral water',
  'milk',
  'eggs',
  'chocolate',
  'french fries',
  'pancakes',
  'low fat yogurt'],
 ['ground beef', 'mineral water', 'antioxydant juice', 'protein bar'],
 ['grated cheese',
  'whole wheat pasta',
  'ground beef',
  'spaghetti',
  'cake',
  'energy drink'],
 ['grated cheese'],
 ['pancakes'],
 ['frozen smoothie'],
 ['carrots', 'green tea'],
 ['chocolate'],
 ['turkey',
  'burgers',
  'chocolate',
  'olive oil',
  'eggs',
  'cooking oil',
  'corn'],
 ['frozen vegetables',
  'tomatoes',
  'pepper',
  'spaghetti',
  'mineral water',
  'pancakes',
  'chicken',
  'chili',
  'tea',
  'french fries',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['ground beef'],
 ['turkey', 'eggs', 'chocolate', 'frozen smoothie', 'tomato juice'],
 ['frozen vegetables', 'cooking oil', 'mashed potato'],
 ['frozen vegetables',
  'ground beef',
  'tomato sauce',
  'mineral water',
  'meatballs',
  'olive oil',
  'light cream',
  'tomato juice'],
 ['red wine',
  'spaghetti',
  'mineral water',
  'soup',
  'milk',
  'eggs',
  'cake',
  'gums',
  'cooking oil',
  'chocolate',
  'frozen smoothie'],
 ['chocolate',
  'tomatoes',
  'spaghetti',
  'mineral water',
  'avocado',
  'milk',
  'olive oil',
  'eggs',
  'rice',
  'french fries',
  'brownies'],
 ['chocolate',
  'shrimp',
  'pasta',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'nonfat milk',
  'eggs'],
 ['turkey',
  'shrimp',
  'pasta',
  'pepper',
  'spaghetti',
  'mineral water',
  'eggs',
  'chicken',
  'french fries'],
 ['cookies'],
 ['turkey', 'tomatoes', 'cake'],
 ['yams',
  'mineral water',
  'soup',
  'milk',
  'pancakes',
  'whole wheat rice',
  'barbecue sauce',
  'carrots',
  'chocolate',
  'champagne'],
 ['rice'],
 ['chocolate', 'milk'],
 ['shrimp', 'pasta', 'frozen vegetables', 'water spray'],
 ['burgers', 'mineral water', 'milk', 'eggs', 'whole wheat rice', 'mint'],
 ['mineral water', 'vegetables mix', 'cake', 'frozen smoothie', 'brownies'],
 ['cookies'],
 ['shrimp', 'pasta', 'chicken', 'chocolate bread'],
 ['shallot'],
 ['shrimp', 'pasta', 'spaghetti', 'eggs', 'hot dogs', 'green tea'],
 ['burgers'],
 ['red wine',
  'ground beef',
  'spaghetti',
  'mineral water',
  'milk',
  'olive oil',
  'strong cheese',
  'light cream',
  'cooking oil'],
 ['burgers',
  'grated cheese',
  'spaghetti',
  'avocado',
  'milk',
  'oil',
  'french fries'],
 ['herb & pepper',
  'whole wheat pasta',
  'ground beef',
  'mineral water',
  'olive oil'],
 ['shrimp', 'pasta', 'yams', 'milk', 'chocolate'],
 ['butter', 'green tea'],
 ['light mayo'],
 ['low fat yogurt'],
 ['herb & pepper', 'shrimp', 'pasta', 'spaghetti', 'milk'],
 ['burgers', 'eggs'],
 ['turkey',
  'herb & pepper',
  'ground beef',
  'soup',
  'avocado',
  'milk',
  'black tea',
  'eggs',
  'barbecue sauce',
  'carrots',
  'cookies',
  'tomato juice',
  'fresh bread'],
 ['cookies'],
 ['escalope'],
 ['pepper', 'french fries', 'strawberries', 'pancakes', 'low fat yogurt'],
 ['frozen vegetables', 'yams', 'chicken', 'honey', 'light mayo'],
 ['chocolate', 'champagne'],
 ['herb & pepper', 'honey', 'cake', 'rice', 'protein bar'],
 ['burgers',
  'chocolate',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'milk',
  'light mayo',
  'asparagus'],
 ['chocolate', 'mineral water', 'corn', 'cottage cheese', 'green tea'],
 ['muffins'],
 ['ham', 'french wine', 'escalope'],
 ['spaghetti', 'milk', 'whole wheat rice', 'mint green tea'],
 ['chocolate', 'body spray'],
 ['frozen vegetables', 'french fries', 'hot dogs'],
 ['candy bars'],
 ['burgers',
  'shrimp',
  'pasta',
  'milk',
  'green tea',
  'french fries',
  'cookies',
  'white wine'],
 ['parmesan cheese', 'ground beef'],
 ['pancakes', 'whole wheat rice', 'candy bars'],
 ['eggs', 'eggplant', 'cookies'],
 ['frozen vegetables', 'mineral water'],
 ['chocolate'],
 ['turkey', 'spaghetti', 'milk', 'whole wheat rice', 'chocolate'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'soup',
  'meatballs',
  'chicken',
  'blueberries',
  'cooking oil',
  'champagne',
  'yogurt cake',
  'protein bar'],
 ['cooking oil', 'tomato juice'],
 ['frozen vegetables', 'milk', 'eggs', 'french fries', 'green tea'],
 ['fresh tuna',
  'spaghetti',
  'olive oil',
  'french wine',
  'eggs',
  'french fries',
  'champagne',
  'pancakes',
  'light mayo'],
 ['red wine', 'honey', 'hot dogs'],
 ['milk', 'bacon', 'eggs', 'french fries', 'fresh bread'],
 ['french fries', 'yogurt cake'],
 ['milk'],
 ['french fries'],
 ['chocolate'],
 ['burgers', 'ham', 'red wine'],
 ['shrimp',
  'pasta',
  'tomatoes',
  'energy bar',
  'french wine',
  'antioxydant juice',
  'french fries',
  'frozen smoothie',
  'brownies'],
 ['green tea'],
 ['low fat yogurt'],
 ['turkey',
  'spaghetti',
  'mineral water',
  'soup',
  'spinach',
  'soda',
  'energy drink',
  'salt'],
 ['turkey', 'eggs'],
 ['bug spray', 'hot dogs'],
 ['oil'],
 ['soup',
  'energy bar',
  'chicken',
  'eggs',
  'cake',
  'french fries',
  'body spray',
  'strawberries'],
 ['spaghetti', 'chocolate', 'yogurt cake'],
 ['turkey', 'mineral water', 'meatballs'],
 ['ground beef',
  'mineral water',
  'chocolate',
  'fromage blanc',
  'bacon',
  'hot dogs'],
 ['frozen vegetables', 'mineral water', 'vegetables mix', 'escalope'],
 ['herb & pepper', 'red wine', 'tomatoes'],
 ['whole wheat pasta', 'olive oil', 'cereals', 'brownies', 'green tea'],
 ['cookies'],
 ['olive oil', 'cookies', 'mushroom cream sauce'],
 ['ground beef', 'pancakes', 'cooking oil', 'gluten free bar', 'light mayo'],
 ['mineral water', 'french fries'],
 ['herb & pepper'],
 ['salmon'],
 ['eggs', 'escalope'],
 ['mineral water', 'tomato juice'],
 ['mineral water'],
 ['shrimp', 'mineral water', 'soup', 'black tea'],
 ['cake', 'frozen smoothie'],
 ['turkey',
  'burgers',
  'grated cheese',
  'tomatoes',
  'chocolate',
  'fromage blanc',
  'honey',
  'whole wheat rice'],
 ['frozen vegetables',
  'ground beef',
  'mineral water',
  'olive oil',
  'pancakes'],
 ['turkey',
  'burgers',
  'ground beef',
  'milk',
  'olive oil',
  'cake',
  'fresh bread'],
 ['whole wheat pasta',
  'ground beef',
  'spaghetti',
  'yams',
  'mineral water',
  'soup',
  'chutney',
  'cereals',
  'energy drink',
  'protein bar'],
 ['eggs', 'whole wheat rice', 'cake', 'green tea', 'escalope'],
 ['ground beef', 'yams', 'soup', 'avocado', 'salmon', 'green tea'],
 ['milk'],
 ['spaghetti', 'chocolate'],
 ['whole wheat pasta', 'honey'],
 ['whole wheat pasta', 'green tea'],
 ['spaghetti', 'meatballs', 'vegetables mix', 'chocolate'],
 ['eggs', 'low fat yogurt'],
 ['fresh tuna',
  'shrimp',
  'pasta',
  'mineral water',
  'olive oil',
  'eggs',
  'cake',
  'brownies',
  'tomato juice'],
 ['mineral water', 'green grapes', 'hot dogs', 'fresh bread'],
 ['frozen vegetables', 'meatballs', 'eggs', 'chocolate'],
 ['chocolate'],
 ['meatballs', 'milk'],
 ['low fat yogurt'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['pepper',
  'chocolate',
  'olive oil',
  'french wine',
  'salmon',
  'rice',
  'light mayo',
  'fresh bread',
  'magazines'],
 ['red wine',
  'french wine',
  'vegetables mix',
  'rice',
  'clothes accessories',
  'hot dogs',
  'green tea'],
 ['burgers',
  'dessert wine',
  'spaghetti',
  'chicken',
  'cake',
  'protein bar',
  'green tea'],
 ['french wine', 'cake', 'fresh bread'],
 ['burgers', 'frozen vegetables', 'flax seed', 'eggs'],
 ['red wine'],
 ['pepper', 'mineral water', 'energy bar', 'green grapes'],
 ['milk', 'eggs', 'cake', 'chocolate', 'french fries', 'green tea'],
 ['french fries'],
 ['almonds'],
 ['burgers', 'mineral water', 'green tea'],
 ['milk', 'pancakes'],
 ['pancakes', 'eggs', 'salt', 'tomato juice'],
 ['mineral water'],
 ['ham', 'spaghetti', 'mineral water', 'olive oil'],
 ['salt', 'tomato juice', 'fresh bread'],
 ['spaghetti', 'mushroom cream sauce'],
 ['spaghetti', 'mineral water', 'eggs', 'pet food'],
 ['frozen vegetables', 'spaghetti'],
 ['energy drink'],
 ['muffins'],
 ['turkey', 'milk'],
 ['cookies'],
 ['chocolate'],
 ['spaghetti',
  'mineral water',
  'eggs',
  'cooking oil',
  'chocolate',
  'escalope'],
 ['shrimp', 'frozen vegetables', 'pepper', 'spaghetti', 'green tea'],
 ['burgers',
  'fresh tuna',
  'red wine',
  'mineral water',
  'french fries',
  'hand protein bar',
  'low fat yogurt'],
 ['pancakes', 'eggs', 'energy drink', 'fresh bread'],
 ['strong cheese',
  'salmon',
  'green tea',
  'french fries',
  'frozen smoothie',
  'hot dogs'],
 ['grated cheese',
  'shrimp',
  'pasta',
  'tomatoes',
  'milk',
  'frozen smoothie',
  'sandwich'],
 ['herb & pepper', 'whole wheat pasta', 'olive oil', 'pancakes', 'eggs'],
 ['spaghetti', 'antioxydant juice'],
 ['chocolate', 'milk', 'almonds', 'eggs', 'strawberries', 'white wine'],
 ['french fries', 'strawberries'],
 ['mineral water'],
 ['eggs'],
 ['escalope'],
 ['cake'],
 ['whole wheat pasta', 'antioxydant juice', 'body spray', 'green tea'],
 ['mineral water', 'oil', 'frozen smoothie'],
 ['french fries', 'champagne'],
 ['chocolate', 'french fries'],
 ['frozen vegetables', 'spaghetti', 'eggs'],
 ['hot dogs'],
 ['chocolate', 'cookies'],
 ['pancakes'],
 ['shrimp', 'butter', 'chicken', 'salmon'],
 ['chocolate', 'cookies', 'babies food'],
 ['pepper', 'spaghetti', 'cake', 'chocolate', 'french fries', 'fresh bread'],
 ['avocado', 'oil', 'cereals', 'french fries'],
 ['herb & pepper',
  'spaghetti',
  'mineral water',
  'spinach',
  'eggs',
  'oil',
  'cooking oil',
  'green tea',
  'shampoo',
  'tomato juice',
  'low fat yogurt'],
 ['herb & pepper',
  'frozen vegetables',
  'ground beef',
  'pepper',
  'spaghetti',
  'mint green tea',
  'french fries'],
 ['french fries'],
 ['green tea', 'tomato juice'],
 ['eggs', 'whole wheat rice', 'chocolate'],
 ['grated cheese',
  'herb & pepper',
  'red wine',
  'spaghetti',
  'mineral water',
  'salmon',
  'eggs',
  'cooking oil',
  'green tea'],
 ['french fries',
  'cookies',
  'shallot',
  'tomato juice',
  'fresh bread',
  'low fat yogurt'],
 ['burgers', 'fresh tuna', 'spaghetti', 'muffins', 'honey'],
 ['herb & pepper', 'ground beef', 'spaghetti', 'eggs', 'chicken'],
 ['grated cheese', 'muffins', 'tomato juice', 'mayonnaise'],
 ['whole wheat pasta',
  'yams',
  'mineral water',
  'muffins',
  'frozen smoothie',
  'hot dogs',
  'energy drink'],
 ['burgers',
  'spaghetti',
  'soup',
  'milk',
  'olive oil',
  'salmon',
  'eggs',
  'blueberries'],
 ['chocolate', 'champagne', 'magazines'],
 ['frozen vegetables',
  'spaghetti',
  'yams',
  'mineral water',
  'french wine',
  'green grapes',
  'rice',
  'chocolate'],
 ['tomato sauce', 'chocolate'],
 ['milk', 'eggs'],
 ['pet food'],
 ['yogurt cake'],
 ['green tea'],
 ['escalope', 'pasta'],
 ['herb & pepper', 'ground beef'],
 ['mineral water', 'honey', 'brownies'],
 ['turkey', 'eggs', 'cake', 'energy drink'],
 ['turkey',
  'burgers',
  'dessert wine',
  'ground beef',
  'soup',
  'salmon',
  'eggs',
  'gums',
  'tomato juice',
  'candy bars'],
 ['spaghetti', 'mineral water', 'chicken'],
 ['turkey', 'ground beef', 'carrots', 'french fries', 'melons'],
 ['mineral water', 'eggs', 'low fat yogurt'],
 ['turkey', 'cooking oil', 'shampoo'],
 ['spaghetti', 'hot dogs'],
 ['chocolate', 'green tea'],
 ['grated cheese',
  'pepper',
  'mineral water',
  'chocolate',
  'eggs',
  'cake',
  'mashed potato',
  'tomato juice'],
 ['chocolate'],
 ['spaghetti', 'olive oil', 'strong cheese', 'pancakes'],
 ['red wine', 'mineral water', 'soup', 'rice', 'cookies'],
 ['red wine', 'shrimp', 'spaghetti'],
 ['green tea'],
 ['mineral water', 'chicken', 'french fries', 'frozen smoothie'],
 ['muffins'],
 ['cake', 'chocolate'],
 ['fresh tuna',
  'tomatoes',
  'mineral water',
  'soup',
  'avocado',
  'meatballs',
  'olive oil'],
 ['turkey', 'french fries'],
 ['burgers',
  'turkey',
  'herb & pepper',
  'ground beef',
  'pancakes',
  'eggs',
  'light cream',
  'rice',
  'champagne',
  'fresh bread'],
 ['escalope'],
 ['chocolate', 'escalope', 'fresh bread'],
 ['ham',
  'spaghetti',
  'french wine',
  'vegetables mix',
  'chocolate',
  'french fries'],
 ['avocado', 'light mayo'],
 ['spaghetti', 'yams', 'butter', 'chocolate'],
 ['energy bar', 'eggs', 'french fries'],
 ['fresh tuna', 'barbecue sauce', 'eggplant'],
 ['energy drink'],
 ['whole wheat rice', 'french fries', 'hot dogs', 'green tea'],
 ['mineral water', 'chicken', 'green tea'],
 ['eggs', 'cake', 'mushroom cream sauce'],
 ['escalope'],
 ['antioxydant juice', 'escalope'],
 ['shrimp', 'spaghetti', 'french fries'],
 ['grated cheese', 'spaghetti', 'salmon', 'tomato juice'],
 ['spaghetti', 'green tea'],
 ['champagne', 'protein bar'],
 ['mineral water', 'avocado', 'chocolate'],
 ['tomatoes', 'champagne', 'green tea'],
 ['chicken', 'french fries', 'escalope'],
 ['frozen vegetables',
  'tomatoes',
  'eggs',
  'green tea',
  'frozen smoothie',
  'light mayo'],
 ['ground beef',
  'chicken',
  'cider',
  'green grapes',
  'honey',
  'chocolate',
  'french fries',
  'champagne',
  'frozen smoothie',
  'escalope'],
 ['french fries', 'champagne'],
 ['mineral water', 'soup'],
 ['frozen vegetables', 'spaghetti', 'milk', 'chocolate', 'babies food'],
 ['honey', 'whole wheat rice'],
 ['whole wheat rice', 'chicken', 'tomato juice'],
 ['pancakes'],

In [18]:
!pip install apriori

Requirement already satisfied: apriori in /usr/local/lib/python3.12/dist-packages (1.3.1)
Requirement already satisfied: cantera>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from apriori) (3.2.0)
Requirement already satisfied: findiff>=0.12 in /usr/local/lib/python3.12/dist-packages (from apriori) (0.13.1)
Requirement already satisfied: matplotlib>=3.2.0 in /usr/local/lib/python3.12/dist-packages (from apriori) (3.10.0)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.12/dist-packages (from apriori) (2.0.2)
Requirement already satisfied: pycsp-lib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from apriori) (1.4.0.post2)
Requirement already satisfied: requests>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from apriori) (2.32.4)
Requirement already satisfied: scipy>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from apriori) (1.16.3)
Requirement already satisfied: tabulate>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from apriori) (0.9.0)
Requirement already satisfied: ruamel.yaml<1,>=0.17.21 in /usr/local/lib/python3.12/dist-packages (from cantera>=3.0.0->apriori) (0.19.1)
Requirement already satisfied: typing_extensions>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from cantera>=3.0.0->apriori) (4.15.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.12/dist-packages (from findiff>=0.12->apriori) (1.14.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.2.0->apriori) (2.9.0.post0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pycsp-lib>=1.4.0->apriori) (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->apriori) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->apriori) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->apriori) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.0->apriori) (2026.5.20)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.2.0->apriori) (1.17.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pycsp-lib>=1.4.0->apriori) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pycsp-lib>=1.4.0->apriori) (2026.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy->findiff>=0.12->apriori) (1.3.0)

In [28]:
from apyori import apriori

In [51]:
rules=apriori(transactions=transaction,min_support=0.003,min_confidence=0.3,min_lift=2,min_length=2,max_length=2)
results=list(rules)
results

[RelationRecord(items=frozenset({'spaghetti', 'bacon'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'bacon'}), items_add=frozenset({'spaghetti'}), confidence=0.36923076923076925, lift=2.1206738131699847)]),
 RelationRecord(items=frozenset({'spaghetti', 'blueberries'}), support=0.0034662045060658577, ordered_statistics=[OrderedStatistic(items_base=frozenset({'blueberries'}), items_add=frozenset({'spaghetti'}), confidence=0.37681159420289856, lift=2.164214217546663)]),
 RelationRecord(items=frozenset({'french fries', 'body spray'}), support=0.004266097853619517, ordered_statistics=[OrderedStatistic(items_base=frozenset({'body spray'}), items_add=frozenset({'french fries'}), confidence=0.37209302325581395, lift=2.17712150346479)]),
 RelationRecord(items=frozenset({'tomato sauce', 'chocolate'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'chocolate'}), confidence=0.3584905660377358, lift=2.1879883936932925)]),
 RelationRecord(items=frozenset({'cider', 'eggs'}), support=0.004266097853619517, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cider'}), items_add=frozenset({'eggs'}), confidence=0.4050632911392405, lift=2.2539909101153137)]),
 RelationRecord(items=frozenset({'cider', 'milk'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cider'}), items_add=frozenset({'milk'}), confidence=0.31645569620253167, lift=2.4421133510444344)]),
 RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'mineral water', 'extra dark chocolate'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'extra dark chocolate'}), items_add=frozenset({'mineral water'}), confidence=0.47777777777777775, lift=2.0043686303753416)]),
 RelationRecord(items=frozenset({'green tea', 'flax seed'}), support=0.0030662578322890282, ordered_statistics=[OrderedStatistic(items_base=frozenset({'flax seed'}), items_add=frozenset({'green tea'}), confidence=0.3382352941176471, lift=2.560144239330445)]),
 RelationRecord(items=frozenset({'green beans', 'spaghetti'}), support=0.0034662045060658577, ordered_statistics=[OrderedStatistic(items_base=frozenset({'green beans'}), items_add=frozenset({'spaghetti'}), confidence=0.39999999999999997, lift=2.29739663093415)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'spaghetti', 'ground beef'}), support=0.03919477403012932, ordered_statistics=[OrderedStatistic(items_base=frozenset({'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.3989145183175034, lift=2.291162176033379)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'milk', 'soup'}), support=0.015197973603519531, ordered_statistics=[OrderedStatistic(items_base=frozenset({'soup'}), items_add=frozenset({'milk'}), confidence=0.3007915567282322, lift=2.3212319619531585)]),
 RelationRecord(items=frozenset({'milk', 'whole wheat pasta'}), support=0.009865351286495135, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'milk'}), confidence=0.33484162895927605, lift=2.5839990317114503)]),
 RelationRecord(items=frozenset({'mineral water', 'nonfat milk'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'nonfat milk'}), items_add=frozenset({'mineral water'}), confidence=0.4871794871794871, lift=2.0438105891126024)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)]),
 RelationRecord(items=frozenset({'spaghetti', 'pepper'}), support=0.009865351286495135, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pepper'}), items_add=frozenset({'spaghetti'}), confidence=0.37185929648241206, lift=2.1357707373005916)]),
 RelationRecord(items=frozenset({'red wine', 'spaghetti'}), support=0.010265297960271964, ordered_statistics=[OrderedStatistic(items_base=frozenset({'red wine'}), items_add=frozenset({'spaghetti'}), confidence=0.36492890995260663, lift=2.095966120638976)]),
 RelationRecord(items=frozenset({'strong cheese', 'spaghetti'}), support=0.0037328356219170776, ordered_statistics=[OrderedStatistic(items_base=frozenset({'strong cheese'}), items_add=frozenset({'spaghetti'}), confidence=0.4827586206896552, lift=2.7727200718170777)]),
 RelationRecord(items=frozenset({'tomato sauce', 'spaghetti'}), support=0.006265831222503666, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'spaghetti'}), confidence=0.4433962264150943, lift=2.546642491837383)])]

In [52]:
rows = []

for rule in results:
    for stat in rule.ordered_statistics:
        rows.append({
                'LHS': list(stat.items_base)[0],
                'RHS': list(stat.items_add)[0],
            'Support': rule.support,
            'Confidence': stat.confidence,
            'Lift': stat.lift
        })

df_rules = pd.DataFrame(rows)

In [53]:
df_rules

                     LHS            RHS   Support  Confidence      Lift
0                  bacon      spaghetti  0.003200    0.369231  2.120674
1            blueberries      spaghetti  0.003466    0.376812  2.164214
2             body spray   french fries  0.004266    0.372093  2.177122
3           tomato sauce      chocolate  0.005066    0.358491  2.187988
4                  cider           eggs  0.004266    0.405063  2.253991
5                  cider           milk  0.003333    0.316456  2.442113
6   mushroom cream sauce       escalope  0.005733    0.300699  3.790833
7                  pasta       escalope  0.005866    0.372881  4.700812
8   extra dark chocolate  mineral water  0.005733    0.477778  2.004369
9              flax seed      green tea  0.003066    0.338235  2.560144
10           green beans      spaghetti  0.003466    0.400000  2.297397
11         herb & pepper    ground beef  0.015998    0.323450  3.291994
12           ground beef      spaghetti  0.039195    0.398915  2.291162
13          tomato sauce    ground beef  0.005333    0.377358  3.840659
14                  soup           milk  0.015198    0.300792  2.321232
15     whole wheat pasta           milk  0.009865    0.334842  2.583999
16           nonfat milk  mineral water  0.005066    0.487179  2.043811
17                 pasta         shrimp  0.005066    0.322034  4.506672
18                pepper      spaghetti  0.009865    0.371859  2.135771
19              red wine      spaghetti  0.010265    0.364929  2.095966
20         strong cheese      spaghetti  0.003733    0.482759  2.772720
21          tomato sauce      spaghetti  0.006266    0.443396  2.546642

In [57]:
df_rules = df_rules.sort_values(by='Lift',ascending=False)
df_rules

                     LHS            RHS   Support  Confidence      Lift
7                  pasta       escalope  0.005866    0.372881  4.700812
17                 pasta         shrimp  0.005066    0.322034  4.506672
13          tomato sauce    ground beef  0.005333    0.377358  3.840659
6   mushroom cream sauce       escalope  0.005733    0.300699  3.790833
11         herb & pepper    ground beef  0.015998    0.323450  3.291994
20         strong cheese      spaghetti  0.003733    0.482759  2.772720
15     whole wheat pasta           milk  0.009865    0.334842  2.583999
9              flax seed      green tea  0.003066    0.338235  2.560144
21          tomato sauce      spaghetti  0.006266    0.443396  2.546642
5                  cider           milk  0.003333    0.316456  2.442113
14                  soup           milk  0.015198    0.300792  2.321232
10           green beans      spaghetti  0.003466    0.400000  2.297397
12           ground beef      spaghetti  0.039195    0.398915  2.291162
4                  cider           eggs  0.004266    0.405063  2.253991
3           tomato sauce      chocolate  0.005066    0.358491  2.187988
2             body spray   french fries  0.004266    0.372093  2.177122
1            blueberries      spaghetti  0.003466    0.376812  2.164214
18                pepper      spaghetti  0.009865    0.371859  2.135771
0                  bacon      spaghetti  0.003200    0.369231  2.120674
19              red wine      spaghetti  0.010265    0.364929  2.095966
16           nonfat milk  mineral water  0.005066    0.487179  2.043811
8   extra dark chocolate  mineral water  0.005733    0.477778  2.004369